project:
  type: website

website:
  title: "Hyouji Joo's Portfolio"
  navbar:
    title: "Portfolio Page"
    left:
      - text: Home
        href: front_page.qmd
      - text: About
        href: about.qmd     
      - text: Projects                     
        menu:      
          - text: ▶ Projects Home
            href: projects.qmd
          - text: Coding 
            href: projects/coding.qmd              
          - text: Marketing 
            href: projects/marketing.qmd
          - text: Design     
            href: projects/design.qmd
          - text: Personal 
            href: projects/personal.qmd 
      
      
format:
  html: 
    css: styles/style.css    
    theme: [default]                           