
project:
  type: website

website:
  title: "My Portfolio"
  navbar:
    title: "My Portfolio"
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        menu:
          - text: Data Science
            href: projects/data_science.qmd
          - text: Marketing 
            href: projects/marketing.qmd
          - text: Graphic Design 
            href: projects/graphic_design.qmd


format:
  html:
    css: styles/styles.css
